name: README

on:
    workflow_dispatch:
    schedule:
        - cron: "0 8 * * 1,3,5"

jobs:
    update-readme:
        name: Update README
        runs-on: ubuntu-latest
        steps:
            - uses: ism0080/comicstrip-readme@v1.2
              with:
                  SHOW_XKCD: true
            - uses: Platane/snk/svg-only@v3
              with:
                  github_user_name: MateusMaceedo
                  outputs: dist/github-snake.svg
            - uses: crazy-max/ghaction-github-pages@v3
              with:
                  target_branch: output
                  build_dir: dist
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
